name: Xiandong QI
title: Xiandong
description: I am a first year PhD student in CSE department of HKUST.
meta_description: "Xiandong"
image: /assets/images/profile.png

markdown: kramdown
highlighter: rouge

baseurl: '/'

logo: false
paginate: 15
permalink: /:title

twitter:
  username: xqiad
# Details for the RSS feed generator
url:            'xiandong79.github.io'
author:         'Xiandong'

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
